#pragma once
// AUTO-GENERATED by tools/gen_i18n.py – do not edit
#include "i18n_keys.h"
// Langs: en, de
#define I18N_LANG_COUNT 2
extern const char *I18N_KEYS[I18N_KEY_COUNT];
extern const char *I18N_EN[I18N_KEY_COUNT];
extern const char *I18N_DE[I18N_KEY_COUNT];
extern const char *I18N_LANG_CODES[I18N_LANG_COUNT];
extern const char **I18N_TABLE[I18N_LANG_COUNT];
// LANG enum mapping: LANG_EN=0 must match order en,de,...
